---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "eirini-pancake-extension"
  namespace: {{ .Values.namespaces.webhook | quote }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eirini-pancake-extension
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: eirini-pancake-extension
roleRef:
  kind: Role
  name: eirini-pancake-extension
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: eirini-pancake-extension
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
    - '*'
